// Mocks generated by Mockito 5.0.15 from annotations
// in kulina_app/test/domain/usecases/get_product_list_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:kulina_app/domain/entities/product.dart' as _i4;
import 'package:kulina_app/domain/repositories/product_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i2.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Product>> getProductList() =>
      (super.noSuchMethod(Invocation.method(#getProductList, []),
              returnValue: Future<List<_i4.Product>>.value(<_i4.Product>[]))
          as _i3.Future<List<_i4.Product>>);
  @override
  String toString() => super.toString();
}
